# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
