# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deployRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='\u53d1\u5e03\u9879\u76ee\u540d')),
                ('project_owner', models.CharField(max_length=32, verbose_name='\u9879\u76ee\u8d1f\u8d23\u4eba')),
                ('deploy_branch', models.CharField(max_length=32, verbose_name='\u53d1\u5e03\u5206\u652f')),
                ('deploy_tag', models.CharField(max_length=32, verbose_name='\u53d1\u5e03\u6807\u7b7e')),
                ('deploy_time', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
