# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('project', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('branch', models.CharField(max_length=32, verbose_name='\u5206\u652f')),
                ('tag', models.CharField(max_length=32, verbose_name='\u6807\u7b7e')),
                ('env', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4efb\u52a1\u73af\u5883')),
                ('config', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u914d\u7f6e\u6587\u4ef6')),
                ('type', models.CharField(max_length=32, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('period', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5b9a\u65f6\u5668')),
                ('status', models.IntegerField(verbose_name='\u72b6\u6001')),
                ('createdate', models.DateField(blank=True, default=datetime.datetime(2017, 10, 24, 16, 38, 43, 515016))),
            ],
        ),
    ]
