# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployrecord',
            name='deploy_time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
