# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_periodtask_projects_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodtask',
            name='createdate',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 10, 24, 16, 40, 3, 619724)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='createdate',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 10, 24, 16, 40, 3, 616563)),
        ),
    ]
