# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20171011_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployrecord',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
