# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20171024_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodtask',
            name='target',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u76ee\u6807'),
        ),
        migrations.AlterField(
            model_name='periodtask',
            name='createdate',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 6, 15, 31, 57, 518278)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='createdate',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 6, 15, 31, 57, 515236)),
        ),
    ]
