# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_deployrecord_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployrecord',
            name='project_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
    ]
