# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20171011_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployrecord',
            name='project_env',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u9879\u76ee\u73af\u5883'),
        ),
    ]
