# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_deployrecord_project_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(max_length=32, verbose_name='\u9879\u76eeID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('ssh_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9879\u76eeSSH\u5730\u5740')),
                ('http_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9879\u76eeHTTP\u5730\u5740')),
                ('branches', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9879\u76ee\u5206\u652f')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9879\u76ee\u6807\u7b7e')),
                ('configfile', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9879\u76ee\u914d\u7f6e')),
                ('owner', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u9879\u76ee\u8d1f\u8d23\u4eba')),
                ('ci_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='Gitlab_CI_Token')),
                ('createdate', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
