# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deployRecord',
            new_name='Records',
        ),
    ]
