# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_remove_projects_ci_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u9879\u76ee\u6807\u7b7e'),
        ),
    ]
