# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmonitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mysql_Replication_History',
        ),
        migrations.DeleteModel(
            name='Mysql_Status_History',
        ),
    ]
