# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmonitor', '0004_auto_20171027_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysql_connection',
            name='connect_db',
        ),
        migrations.RemoveField(
            model_name='mysql_connection',
            name='connect_server',
        ),
        migrations.RemoveField(
            model_name='mysql_connection',
            name='connect_user',
        ),
        migrations.AddField(
            model_name='mysql_connection',
            name='max_connect',
            field=models.CharField(max_length=32, null=True, verbose_name='\u6700\u5927\u8fde\u63a5\u6570'),
        ),
        migrations.AddField(
            model_name='mysql_connection',
            name='thead_connect',
            field=models.CharField(max_length=32, null=True, verbose_name='\u5f53\u524d\u8fde\u63a5\u6570'),
        ),
        migrations.AlterField(
            model_name='mysql_connection',
            name='connect_count',
            field=models.CharField(max_length=32, null=True, verbose_name='\u8fde\u63a5\u603b\u6570'),
        ),
    ]
