# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmonitor', '0007_auto_20171030_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql_connection',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mysql_processlist',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mysql_replication',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mysql_status',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
