# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbmonitor', '0008_auto_20171031_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mysql_Processlist',
        ),
        migrations.AlterField(
            model_name='mysql_connection',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 3, 40, 33, 65614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mysql_replication',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 3, 40, 33, 22362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mysql_status',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 3, 40, 33, 73799, tzinfo=utc)),
        ),
    ]
