# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 09:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbmonitor', '0010_auto_20171031_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mysql_Processlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('db_ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6570\u636e\u5e93ip')),
                ('db_port', models.IntegerField(default=3306)),
                ('db_user', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6570\u636e\u5e93\u7528\u6237')),
                ('db', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6570\u636e\u5e93')),
                ('connected_host', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u8fde\u63a5\u4e3b\u673a')),
                ('command', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u547d\u4ee4')),
                ('state', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u72b6\u6001')),
                ('info', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4fe1\u606f')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 10, 31, 17, 14, 19, 543188, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='mysql_connection',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 17, 14, 19, 548220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mysql_replication',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 17, 14, 19, 545692, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mysql_status',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 17, 14, 19, 555431, tzinfo=utc)),
        ),
    ]
