# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network_Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('private_incoming', models.FloatField(blank=True, null=True)),
                ('private_outgoing', models.FloatField(blank=True, null=True)),
                ('global_incoming', models.FloatField(blank=True, null=True)),
                ('global_outgoing', models.FloatField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 11, 3, 11, 40, 50, 770973, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Nginx_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('reading', models.IntegerField(blank=True, null=True)),
                ('writing', models.IntegerField(blank=True, null=True)),
                ('waiting', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 11, 3, 11, 40, 50, 768713, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Online_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 11, 3, 11, 40, 50, 769803, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Tcp_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('listen', models.IntegerField(blank=True, null=True)),
                ('established', models.IntegerField(blank=True, null=True)),
                ('time_wait', models.IntegerField(blank=True, null=True)),
                ('close_wait', models.IntegerField(blank=True, null=True)),
                ('closed', models.IntegerField(blank=True, null=True)),
                ('syn_sent', models.IntegerField(blank=True, null=True)),
                ('syn_received', models.IntegerField(blank=True, null=True)),
                ('last_ack', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 11, 3, 11, 40, 50, 767218, tzinfo=utc))),
            ],
        ),
    ]
