# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server_NetWorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField()),
                ('tcp_status', models.CharField(blank=True, max_length=128, null=True, verbose_name='TCP\u72b6\u6001')),
                ('network_incoming', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u516c\u7f51\u6d41\u5165')),
                ('network_outcoming', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u516c\u7f51\u6d41\u51fa')),
            ],
        ),
        migrations.CreateModel(
            name='Server_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField()),
                ('service_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u670d\u52a1\u540d\u79f0')),
                ('service_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u670d\u52a1\u72b6\u6001')),
                ('service_port', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u670d\u52a1\u7aef\u53e3')),
                ('service_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u670d\u52a1\u7248\u672c')),
                ('service_cmd', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u542f\u52a8\u547d\u4ee4')),
            ],
        ),
    ]
