# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docker_Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('container_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bb9\u5668ID')),
                ('container_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bb9\u5668\u540d')),
                ('image_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u955c\u50cf\u540d')),
                ('command', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u542f\u52a8\u547d\u4ee4')),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6301\u7eed\u65f6\u95f4')),
                ('state', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bb9\u5668\u72b6\u6001')),
                ('create_date', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Docker_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u955c\u50cfID')),
                ('image_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u955c\u50cf\u540d')),
                ('size', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u955c\u50cf\u5927\u5c0f')),
                ('create_date', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('system', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7cfb\u7edf\u5e73\u53f0')),
                ('glabal_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e3b\u673a\u516c\u7f51IP')),
                ('private_ip', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e3b\u673a\u79c1\u7f51IP')),
                ('cpu_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU')),
                ('mem_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5185\u5b58')),
                ('hdd_storage', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u786c\u76d8')),
                ('net_flow', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u7f51\u5361\u5e26\u5bbd')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u662f\u5426\u5728\u7ebf')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Server_NetWorkStatus',
        ),
    ]
