# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='CpuStat',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='server',
            name='MemoryStat',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5185\u5b58'),
        ),
        migrations.AlterField(
            model_name='server',
            name='Status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u662f\u5426\u6fc0\u6d3b'),
        ),
    ]
