# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docker_Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostName', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('containerName', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5bb9\u5668\u540d')),
                ('imageName', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u955c\u50cf\u540d')),
                ('command', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u542f\u52a8\u547d\u4ee4')),
                ('created', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('status', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u5bb9\u5668\u72b6\u6001')),
            ],
        ),
        migrations.RenameField(
            model_name='server_status',
            old_name='login_user',
            new_name='loginUser',
        ),
        migrations.RenameField(
            model_name='server_status',
            old_name='server_id',
            new_name='serverId',
        ),
        migrations.AddField(
            model_name='server_status',
            name='cpuLoad',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU\u8d1f\u8f7d'),
        ),
        migrations.AddField(
            model_name='server_status',
            name='globalNetcardIncome',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u516c\u7f51\u8fdb\u6d41\u91cf'),
        ),
        migrations.AddField(
            model_name='server_status',
            name='globalNetcardOutgo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u516c\u7f51\u51fa\u6d41\u91cf'),
        ),
        migrations.AddField(
            model_name='server_status',
            name='memLoad',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u5b58\u8d1f\u8f7d'),
        ),
        migrations.AddField(
            model_name='server_status',
            name='privateNetcardIncome',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u79c1\u7f51\u8fdb\u6d41\u91cf'),
        ),
        migrations.AddField(
            model_name='server_status',
            name='privateNetcardOutgo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u79c1\u7f51\u51fa\u6d41\u91cf'),
        ),
        migrations.AddField(
            model_name='server_status',
            name='procNum',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8fdb\u7a0b\u6570'),
        ),
    ]
