# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20170424_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker_container',
            name='command',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u542f\u52a8\u547d\u4ee4'),
        ),
        migrations.AlterField(
            model_name='docker_container',
            name='containerName',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bb9\u5668\u540d'),
        ),
        migrations.AlterField(
            model_name='docker_container',
            name='created',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='docker_container',
            name='imageName',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u955c\u50cf\u540d'),
        ),
        migrations.AlterField(
            model_name='docker_container',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bb9\u5668\u72b6\u6001'),
        ),
    ]
