# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20171106_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='salt_alias',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='salt\u522b\u540d'),
        ),
    ]
