# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20170424_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker_container',
            name='containerId',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bb9\u5668ID'),
        ),
    ]
