# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_docker_container_containerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docker_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u955c\u50cf\u540d')),
                ('created', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('size', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u955c\u50cf\u5927\u5c0f')),
            ],
        ),
    ]
