# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_docker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker_image',
            name='imageName',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u955c\u50cf\u540d'),
        ),
    ]
