# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20170424_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docker_container',
            old_name='created',
            new_name='createdate',
        ),
        migrations.AddField(
            model_name='docker_container',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5bb9\u5668\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='docker_container',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6301\u7eed\u65f6\u95f4'),
        ),
    ]
