# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20171010_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docker_image',
            old_name='created',
            new_name='createdate',
        ),
    ]
