# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20171010_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker_image',
            name='imageId',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u955c\u50cfID'),
        ),
    ]
