# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u811a\u672c\u540d\u79f0')),
                ('content', models.CharField(max_length=255, null=True, verbose_name='\u811a\u672c\u5185\u5bb9')),
                ('params', models.CharField(max_length=255, null=True, verbose_name='\u811a\u672c\u53c2\u6570')),
                ('path', models.FileField(upload_to=b'', verbose_name='\u521b\u5efa\u8def\u5f84')),
                ('created', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u7528\u6237\u540d')),
                ('roler', models.CharField(max_length=32, verbose_name='\u6743\u9650\u89d2\u8272')),
                ('uid', models.IntegerField()),
                ('gid', models.IntegerField()),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptId', models.IntegerField()),
                ('executeTime', models.DateField(null=True, verbose_name='\u6267\u884c\u65f6\u95f4')),
                ('targets', models.CharField(max_length=255, verbose_name='\u76ee\u6807')),
                ('timeout', models.DateField(null=True, verbose_name='\u8d85\u65f6')),
            ],
        ),
        migrations.CreateModel(
            name='UploadScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='\u811a\u672c\u540d\u79f0')),
                ('params', models.CharField(max_length=255, null=True, verbose_name='\u811a\u672c\u53c2\u6570')),
                ('path', models.FileField(upload_to='../files/', verbose_name='\u4e0a\u4f20\u8def\u5f84')),
                ('created', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
