# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpuload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.CharField(max_length=32)),
                ('avg1', models.CharField(max_length=32)),
                ('avg5', models.CharField(max_length=32)),
                ('avg15', models.CharField(max_length=32)),
                ('created', models.DateField(default=datetime.datetime(2017, 10, 18, 8, 3, 58, 736029), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cpustat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.CharField(max_length=32)),
                ('system', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                ('idle', models.CharField(max_length=32)),
                ('iowait', models.CharField(max_length=32)),
                ('nice', models.CharField(max_length=32)),
                ('softirq', models.CharField(max_length=32)),
                ('steal', models.CharField(max_length=32)),
                ('interrupt', models.CharField(max_length=32)),
                ('created', models.DateField(default=datetime.datetime(2017, 10, 18, 8, 3, 58, 733254), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='memstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.CharField(max_length=32)),
                ('available', models.CharField(max_length=32)),
                ('total', models.CharField(max_length=32)),
                ('created', models.DateField(default=datetime.datetime(2017, 10, 18, 8, 3, 58, 737858), null=True)),
            ],
        ),
    ]
