# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpuload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg1', models.CharField(max_length=32)),
                ('avg5', models.CharField(max_length=32)),
                ('avg15', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='cpustat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                ('idle', models.CharField(max_length=32)),
                ('iowait', models.CharField(max_length=32)),
                ('nice', models.CharField(max_length=32)),
                ('softirq', models.CharField(max_length=32)),
                ('steal', models.CharField(max_length=32)),
                ('interrupt', models.CharField(max_length=32)),
                ('created', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='memstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.CharField(max_length=32)),
                ('total', models.CharField(max_length=32)),
                ('created', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
