# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-10 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbixapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuload',
            name='created',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
