# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 02:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbixapi', '0002_cpuload_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuload',
            name='created',
            field=models.DateField(default=datetime.datetime(2017, 5, 17, 2, 36, 12, 569043), null=True),
        ),
        migrations.AlterField(
            model_name='cpustat',
            name='created',
            field=models.DateField(default=datetime.datetime(2017, 5, 17, 2, 36, 12, 568316), null=True),
        ),
        migrations.AlterField(
            model_name='memstat',
            name='created',
            field=models.DateField(default=datetime.datetime(2017, 5, 17, 2, 36, 12, 569813), null=True),
        ),
    ]
