# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-17 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbixapi', '0003_auto_20170517_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpuload',
            name='created',
            field=models.DateField(default=datetime.datetime(2017, 5, 17, 9, 45, 29, 825210), null=True),
        ),
        migrations.AlterField(
            model_name='cpustat',
            name='created',
            field=models.DateField(default=datetime.datetime(2017, 5, 17, 9, 45, 29, 824339), null=True),
        ),
        migrations.AlterField(
            model_name='memstat',
            name='created',
            field=models.DateField(default=datetime.datetime(2017, 5, 17, 9, 45, 29, 825800), null=True),
        ),
    ]
